name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 4.5.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/share_plus
publish_to: none
flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin

dependencies:
  cross_file: ^0.3.3+2
  meta: ^1.7.0
  mime: ^1.0.2
  flutter:
    sdk: flutter
  share_plus_platform_interface:
    git:
      url: https://github.com/GuangAD/share_plus_excluding_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
